spring:
  application:
    name: notification-service
  mail:
    username: darek.giza.codete.pl@gmail.com
    password: Dg@12345
    host: smtp.gmail.com
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.port: 465
server:
  port: 8086
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://server:8761/eureka/
    availability-zones:
      region1: zone1

