version: '3.5'
services:
  server:
    build:
      context: ./server
    hostname: server
    container_name: server
    environment:
      - SPRING_APPLICATION_NAME=server
      - SPRING_PROFILES_ACTIVE=dev
    command: ["mvn", "spring-boot:run"]
    ports:
      - "8761:8761"
    expose:
      - "8761"
    volumes:
      - maven-home:/root/.m2
    networks:
      services-network:
        aliases:
          - server

  user-service:
    build:
      context: ./user-service
    hostname: user-service
    container_name: user-service
    environment:
      - SERVICE_CHECK_HTTP=/health
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_PROFILES_ACTIVE=dev
    command: ["mvn", "spring-boot:run"]
    ports:
      - "8085:8085"
    volumes:
      - maven-home:/root/.m2
    networks:
      services-network:
        aliases:
          - user-service
    depends_on:
      app-mongo:
        condition: service_started

  gateway:
    build:
      context: ./gateway
    hostname: gateway
    container_name: gateway
    environment:
      - SERVICE_CHECK_HTTP=/health
      - SPRING_APPLICATION_NAME=gateway
      - SPRING_PROFILES_ACTIVE=dev
    command: [ "mvn", "spring-boot:run" ]
    ports:
      - "8084:8084"
    volumes:
      - maven-home:/root/.m2
    networks:
      services-network:
        aliases:
          - gateway
    depends_on:
      server:
        condition: service_started

  app-mongo:
    image: 'mongo:4.2.7-bionic'
    ports:
    - 27017:27017
    container_name: app-mongo
    restart: always
    depends_on:
      server:
        condition: service_started
    networks:
      services-network:
        aliases:
          - app-mongo

volumes:
  maven-home:

networks:
  services-network:
    name: services-network
    driver: bridge









