server:
  port: 8085
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://server:8761/eureka/
    availability-zones:
      region1: zone1
spring:
  application:
    name: user-service
  data:
    mongodb:
      database: local
      uri: mongodb://app-mongo:27017/
      auto-index-creation: true

